#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-tfautograph
Version  : 0.3.2
Release  : 2
URL      : https://cran.r-project.org/src/contrib/tfautograph_0.3.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tfautograph_0.3.2.tar.gz
Summary  : Autograph R for 'Tensorflow'
Group    : Development/Tools
License  : GPL-3.0
Requires: R-backports
Requires: R-reticulate
BuildRequires : R-backports
BuildRequires : R-reticulate
BuildRequires : buildreq-R

%description
# tfautograph
<!-- badges: start -->
[![CRAN status](https://www.r-pkg.org/badges/version/tfautograph)](https://CRAN.R-project.org/package=tfautograph)
[![R build status](https://github.com/t-kalinowski/tfautograph/workflows/R-CMD-check/badge.svg)](https://github.com/t-kalinowski/tfautograph/actions?workflow=R-CMD-check)
<!-- badges: end -->

%prep
%setup -q -c -n tfautograph
cd %{_builddir}/tfautograph

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641137254

%install
export SOURCE_DATE_EPOCH=1641137254
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tfautograph
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tfautograph
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library tfautograph
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc tfautograph || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tfautograph/DESCRIPTION
/usr/lib64/R/library/tfautograph/INDEX
/usr/lib64/R/library/tfautograph/Meta/Rd.rds
/usr/lib64/R/library/tfautograph/Meta/features.rds
/usr/lib64/R/library/tfautograph/Meta/hsearch.rds
/usr/lib64/R/library/tfautograph/Meta/links.rds
/usr/lib64/R/library/tfautograph/Meta/nsInfo.rds
/usr/lib64/R/library/tfautograph/Meta/package.rds
/usr/lib64/R/library/tfautograph/NAMESPACE
/usr/lib64/R/library/tfautograph/NEWS.md
/usr/lib64/R/library/tfautograph/R/tfautograph
/usr/lib64/R/library/tfautograph/R/tfautograph.rdb
/usr/lib64/R/library/tfautograph/R/tfautograph.rdx
/usr/lib64/R/library/tfautograph/help/AnIndex
/usr/lib64/R/library/tfautograph/help/aliases.rds
/usr/lib64/R/library/tfautograph/help/figures/README-pressure-1.png
/usr/lib64/R/library/tfautograph/help/paths.rds
/usr/lib64/R/library/tfautograph/help/tfautograph.rdb
/usr/lib64/R/library/tfautograph/help/tfautograph.rdx
/usr/lib64/R/library/tfautograph/html/00Index.html
/usr/lib64/R/library/tfautograph/html/R.css
/usr/lib64/R/library/tfautograph/tests/run-tests
/usr/lib64/R/library/tfautograph/tests/testthat.R
/usr/lib64/R/library/tfautograph/tests/testthat/helper-utils.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-break.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-export-modified.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-for.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-hints.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-if.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-map.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-stopifnot.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-switch.R
/usr/lib64/R/library/tfautograph/tests/testthat/test-while.R
